# FILE: config/models.yml
# V2.1: Updated comments to reflect the agent's use of Gemini for re-ranking.

models:
  synthesis_pro: 'gemini-1.5-pro-latest'
  synthesis_flash: 'gemini-1.5-flash-latest'
  classification: 'gemini-1.5-flash-latest'
  embedding: 'models/text-embedding-004'

# --- Re-ranker Configuration ---
# NOTE: The agent currently uses a prompt-based re-ranking strategy with the
# 'classification' model (gemini-1.5-flash-latest) specified above.
# A dedicated re-ranker model could be a future performance enhancement.
reranker:
  model_name: "gemini-1.5-flash-latest" # This is for reference; the agent code selects the model directly.