# FILE: config/persona_tool_map.yml
# V3.0 (Unified Tooling): Refactored to use a single vector search tool with persona-driven metadata hints.

clinical_analyst:
  - tool_name: "vector_search"
    weight: 1.0
    # Hint: Prioritize chunks marked with these semantic purposes
    metadata_hints:
      semantic_purpose: ["Efficacy Results", "Safety Results", "Clinical Trial Design", "Indication/Population Description"]
  - tool_name: "query_knowledge_graph"
    weight: 0.9

health_economist:
  - tool_name: "vector_search"
    weight: 1.0
    metadata_hints:
      semantic_purpose: ["Pharmacoeconomic Analysis", "Drug/Therapy Description"]
  - tool_name: "query_knowledge_graph"
    weight: 0.7

regulatory_specialist:
  - tool_name: "vector_search"
    weight: 1.0
    metadata_hints:
      semantic_purpose: ["Regulatory History", "Background/Context", "Dosage and Administration"]
  - tool_name: "query_knowledge_graph"
    weight: 0.9

default:
  - tool_name: "vector_search"
    weight: 1.0
  - tool_name: "query_knowledge_graph"
    weight: 0.8